### ISSUE TITLE
Implementation of state-of-the-art personal detection

### ISSUE THREAD

**Issue by GuillaumeMacaigne** [iwatake2222/play_with_tflite#6]
Hi, 
Love your repo, great work!
I don't know if you've seen [NikolasEnt's work on segmentation with tflite](https://github.com/NikolasEnt/PersonMask_TFLite). It can reach ~20fps on CPU while Deeplab_v3 reaches ~2-3 on the same CPU.
The problem is I can't seem to make it work on Windows. 
Could you implement this on your repo, it could be a very nice contribution to your work ?
Thanks!

**Comment by GuillaumeMacaigne** [comment]
I'm relatively new to this, any big picture guideline if I just wanted to replace the tflite model in your Deeplabv3 by another tflite model (Like that one)?

Thanks anyway, I look forward to your update :)

**Comment by iwatake2222** [comment]
You can just replace model file name here
https://github.com/iwatake2222/play_with_tflite/blob/master/pj_tflite_ss_deeplabv3_mnv2/ImageProcessor/ImageProcessor.cpp#L35

By doing this, you will be able to "run" the model. However, you may get crash error...
You also need to modify pre process and post process logic for the model. The way to modify the code depends on what kind of pre/post process the model requires. You need to import those logic from the original repo.
(Since the model is semantic segmentation, I think the logic is very simple)

**Comment by GuillaumeMacaigne** [comment]
Thank you!

**Comment by iwatake2222** [comment]
I added a new project for this.
https://github.com/iwatake2222/play_with_tflite/tree/master/pj_tflite_ss_person_mask

**Comment by GuillaumeMacaigne** [comment]
Thank you very much!
